version: '3'
services:
  pgsql:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: Tticb06
      POSTGRES_DB: openex
    volumes:
      - pgsqldata:/var/lib/postgresql/data
    restart: always
  minio:
    image: minio/minio:RELEASE.2022-10-08T20-11-00Z
    volumes:
      - s3data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: =adminminio
      MINIO_ROOT_PASSWORD: =Tticb06
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always
  openex:
    image: openexhq/platform:v3.2.1
    environment:
      - SERVER_SSL_KEY-STORE-PASSWORD=grupoTRCMagic
      - OPENEX_BASE-URL=http://localhost:8080
      - OPENEX_AUTH-LOCAL-ENABLE=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pgsql:5432/openex
      - SPRING_DATASOURCE_USERNAME=dbadmin
      - SPRING_DATASOURCE_PASSWORD=Tticb06
      - MINIO_ENDPOINT=minio
      - MINIO_ACCESS-KEY=adminminio
      - MINIO_ACCESS-SECRET=Tticb06
      - SPRING_MAIL_HOST=smtps.gnet.es
      - SPRING_MAIL_PORT=25
      - SPRING_MAIL_USERNAME=openex@grupotrc.com
      - SPRING_MAIL_PASSWORD=ChangeMetrc2022*
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST=*
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE=false
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=false
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=false
      - OPENEX_MAIL_IMAP_ENABLED=false
    ports:
      - "8080:8080"
    depends_on:
      - pgsql
      - minio
    restart: always
volumes:
  pgsqldata:
  s3data:
